version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: cadastro_ninja
    environment:
      POSTGRES_DB: cadastro_ninja
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    restart: always
